### ISSUE TITLE
Production Revamp Scripts

### ISSUE THREAD

**Issue by Jayshua83** [johnwayne1930/FS22_PalletWarehouse#2]
Would you be able and willing to convert your scripts in this mod to use the scripts that are included with Production Revamp? They are wrote by the same person but the ones in PR are newer with more features and do not need to be included in any mod that uses them!

Thanks!

**Comment by johnwayne1930** [comment]
Hello! I am aware of Revamp and who is involved with it. Maybe I'll do a Revamp- version of this mod at some point, but as I personaly don't want to use Revamp productions this would have minor priority for me.

**Comment by Jayshua83** [comment]
Ah ok. :(

Darn. lol

**Comment by johnwayne1930** [comment]
But there still is the Underground Storage from Achimobil, which utilize Revamp.

**Comment by johnwayne1930** [comment]
@Jayshua83 I had the need to use Revamp for another mod, so I figured I can do the Revamp version of this as well.
Should be released in ModHub today.
